FORMAT: 1A
HOST: http://www.google.com

# Identity API
Identity API is a service which manage users and its preferences.

# Group Authentication
Authentication resources

## Authentication [/auth]
### Subscribe to the service [POST]
+ Request (application/json)

        {
            "email" : "test@gmail.com",
            "password" : "123",
            "pseudo" : "toto",
            "persmission" : "ROLE_USER",
            "favoriteProviderForNotification" : "FACEBOOK"
        }

+ Response 200 (application/json)

        {
            "httpCode" : 200,
            "result" : {
                "id" : "1" ,
                "email" : "test@gmail.com",
                "password" : "NULL" ,
                "pseudo" : "toto",
                "permission":"ROLE_USER",
                "favoriteProviderForNotification" : "FACEBOOK",
                "connectionKey":"dGVzdEBnbWFpbC5jb206MTM4NDI2MzM2Njo3NzFhZDMxN2JkYTVhNjdmZjZiNmVkNWJmZGQzNTY3MDgxNzM1MmFkY2RhYTAyMDkzZTBjY2VjZWNkYmE0MmQ2",
                "connectionKeyCreatedDate":1383658566439
            }
        }

### Logout from the service [DELETE]

+ Response 200 (application/json)

        {
           "httpCode": 200,
           "result": "Logout with success"
        }

## Authentication [/auth/subscribe/{nickname}/{email}/{password}]
+ Parameters
    + nickname (required, string, `foobar`) ... String `foobar` of the user which want to login.
    + email (required, string, `dummy@dummy.com`) ... String `email` of the user which want to login.
    + password (required, string, `secret`) ... String `paswword` of the user which want to login.
    
### Subscribe to the service [POST]

+ Response 200 (application/json)

        {
            "httpCode" : 200,
            "result" : {
                "nickname": "foobar",
                "authorities": "ROLE_USER",
                "credentialList": [{
                    identity: "dummy@dummy.com",
                    secret: "password",
                    domain: "internal"
                    }],
                "connectionKey":"dGVzdEBnbWFpbC5jb206MTM4NDI2MzM2Njo3NzFhZDMxN2JkYTVhNjdmZjZiNmVkNWJmZGQzNTY3MDgxNzM1MmFkY2RhYTAyMDkzZTBjY2VjZWNkYmE0MmQ2",
                "connectionKeyCreatedDate":1383658566439
            }
        }


## Login [/login?username={username}&password={password}]
+ Parameters
    + username (required, string, `dummy@dummy.com`) ... String `username` of the user which want to login.
    + password (required, string, `secret`) ... String `paswword` of the user which want to login.

### Log to the service [GET]
    
+ Response 200 (application/json)

        {
            "httpCode" : 200,
            "result" : {
                "id" : "1" ,
               "email" : "test@gmail.com",
                "pseudo" : "toto",
                "permission":"ROLE_USER",
                "favoriteProviderForNotification" : "FACEBOOK",
                "connectionKey":"dGVzdEBnbWFpbC5jb206MTM4NDI2MzM2Njo3NzFhZDMxN2JkYTVhNjdmZjZiNmVkNWJmZGQzNTY3MDgxNzM1MmFkY2RhYTAyMDkzZTBjY2VjZWNkYmE0MmQ2",
                "connectionKeyCreatedDate":1383658566439
            }
        }


# Group User
User resources

## Single User [/user/{user_id}]
+ Parameters
    + user_id (required, number, `1`) ... Number `id` of the user.

### Retreive single user [GET]

+ Response 200 (application/json)

        {
           "httpCode": 200,
           "errorResponse": null,
           "result":
           {
               "id": 1,
               "email": "test@gmail.com",
               "password": null,
               "pseudo": "test",
               "permission": "ROLE_USER",
               "favoriteProviderForNotification" : "FACEBOOK",
               "connectionKey": null,
               "connectionKeyCreatedDate": null
           }
        }

### Update single user [PUT]

+ Response 200 (application/json)

        {
           "httpCode": 200,
           "result" : {
                "id" : "1",
                "email" : "test@gmail.com",
                "password" : "NULL" ,
                "pseudo" : "totor",
                "permission":"ROLE_USER",
                "favoriteProviderForNotification" : "TWITTER",
                "connectionKey":"dGVzdEBnbWFpbC5jb206MTM4NDI2MzM2Njo3NzFhZDMxN2JkYTVhNjdmZjZiNmVkNWJmZGQzNTY3MDgxNzM1MmFkY2RhYTAyMDkzZTBjY2VjZWNkYmE0MmQ2",
                "connectionKeyCreatedDate":1383658566439
            }
        }

### Delete single user [DELETE]

+ Response 200 (application/json)

        {
            "httpCode": 200,
            "result" : "User Deleted"
        }


## User List [/user/list]

### Retreive user list [GET]

+ Response 200 (application/json)

        {
           "httpCode": 200,
           "result" : [{
                "id" : "1",
                "email" : "test@gmail.com",
                "password" : "NULL" ,
                "pseudo" : "totor",
                "permission":"ROLE_USER",
                "favoriteProviderForNotification" : "TWITTER",
                "connectionKey":"dGVzdEBnbWFpbC5jb206MTM4NDI2MzM2Njo3NzFhZDMxN2JkYTVhNjdmZjZiNmVkNWJmZGQzNTY3MDgxNzM1MmFkY2RhYTAyMDkzZTBjY2VjZWNkYmE0MmQ2",
                "connectionKeyCreatedDate":1383658566439
           }, {
                "id" : "2",
                "email" : "test2@gmail.com",
                "password" : "NULL" ,
                "pseudo" : "totor2",
                "permission":"ROLE_USER",
                "favoriteProviderForNotification" : "TWITTER",
                "connectionKey":"zefVzdEBnbWFpbC5jb206MTM4NDI2MzM2Njo3NzFhZDMxN2JkYTVhNjdmZjZiNmVkNWJmZGQzNTY3MDgxNzM1MmFkY2RhYTAyMDkzZTBjY2VjZWNkYmE0MmQ2",
                "connectionKeyCreatedDate":1383658566437
           }]
        }