FORMAT: 1A
HOST: http://www.google.com

# Identity API

Identity API is a service which manage users and its preferences.

# Group Data

Manage user data


## Retreive all users having a specific key-value data [/identity/rest/data]

### Get all users [POST]

+ Needs ROLE_ADMIN role.

+ Request (application/json)

    + Headers
    
            token: the token of currently connected user

    + Body
    
            {
                "key": "idGCM",
                "value" : "12"
            }

+ Response 200 (application/json)

            [
                {
                    "id": 56,
                    "credentialList":
                    [
                        {
                            "identity" : "identity@mail.com",
                            "domain" : "internal",
                            "connected" : true,
                            "id" : 57,
                            "userId" : 56,
                            "password": "",
                            "accessToken": null
                        }    
                    ]
                },
                {
                    "id": 70,
                    "credentialList":
                    [
                        {
                            "identity" : "jeantomate.3",
                            "domain" : "FACEBOOK",
                            "connected" : true
                        }    
                    ]
                }
            ]

# Group Admin

Aministration verbs

## Status [/status]

### Live test [GET]

+ Check if api is alive
    
+ Response 200 (application/json)

        {
            "result" : "OK"
        }
        
# Group Authentication

Authentication resources


## Authentication [/identity/rest/auth/internal/connect]

### Connect with an internal account [POST]

+ Move the connection from userA (deviceUser) to userB with internal credential
+ If userA have no device credential, an error occurs
+ If data is passed in request data, userB will have this data
+ If userB exists:
+ - token and tokenDate of userA are cleared
+ If userB does not exists:
+ - token and tokenDate of userA are cleared
+ - data of userA are cleared
+ - data are copied to userB
+ - if data is passed in request data, it will be merged with existing userB's data
+ All device credentials of the connected user is moved to a new user

+ Request (application/json)

    + Headers
    
            token: tokenid of userA
            
    + Body
    
            {
                "identity" : "identity@mail.com",
                "password" : "12345678",
                "data" : {
                    "name":"jean",
                    "lastname":"blaguin"
                }
            }
            
+ Response 200 (application/json)

        {
            "id": 56,
            "data" : {
                "name":"jean",
                "lastname":"blaguin"
            },
            "service": {
                "id": 2,
                "name": "OFC",
                "version": "1.0",
                "uniqueDataKeys": ["email"]
            },
            "roleList":
            [
                "ROLE_USER"
            ],
            "token": "3bfb25b7a9c40e895b7121c30fdfbaded84fbf5f12b88788839b4011c8ca3ee189abe5aa4b82d92c",
            "tokenDate": 1387553949708,
            "tokenExpirationDate": 1387554190248,
            "credentialList":
            [
                {
                    "identity" : "identity@mail.com",
                    "domain" : "INTERNAL",
                    "connected" : true,
                    "password": "",
                    "accessToken": null
                }    
            ]    
        }

## Social disconnection [/identity/rest/auth/internal/disconnect]

### Remove internal connection for this user [GET]

+ User must at least have one credential after disconnection, otherwise an exception is thrown
+ If user have no internal credential, an exception is thrown

+ Request

    + Headers
    
            token: the token of currently connected user
            
+ Response 200 (application/json)
    
        {
            "id": 56,
            "data" : {
                "name":"jean",
                "lastname":"blaguin"
            },
            "service": {
                "id": 2,
                "name": "OFC",
                "version": "1.0",
                "uniqueDataKeys": ["email"]
            },
            "roleList":
            [
                "ROLE_USER"
            ],
            "token": "3bfb25b7a9c40e895b7121c30fdfbaded84fbf5f12b88788839b4011c8ca3ee189abe5aa4b82d92c",
            "tokenDate": 1387553949708,
            "tokenExpirationDate": 1387554190248,
            "credentialList":
            [
                {
                    "identity" : "identity@mail.com",
                    "domain" : "DEVICE",
                    "userId" : 56,
                    "password": "",
                    "accessToken": "aeeaaezezfs"
                }    
            ]    
        }

## Authentication [/identity/rest/auth/merge]
    
### Merge account with connected user [POST]

+ Merge an existing account (userA) with an another
+ If account (identity/password) exist (userB):
+ - all userA accesses are moved to userB
+ - Data field is merged, if conflict (same data key) userB data key will be kept.
+ - If data is passed in request, it will overwrite the merged data.
+ - userA is removed
+ If no account exists with (identity/password), identity/password are merged in userA (except if userA have already an identity/password access).
+ A user could'nt have more than one identity/password access, an error wil occurs if userA have already an identity/password access.

+ Request (application/json)

    + Headers
    
            token: tokenid of userA
            
    + Body
    
            {
                "identity" : "identity@mail.com",
                "password" : "12345678",
                "data" : {
                    "name":"jean",
                    "lastname":"blaguin"
                }
            }

+ Response 200 (application/json)

        {
            "id": 56,
            "data" : {
                "name":"jean",
                "lastname":"blaguin"
            },
            "service": {
                "id": 2,
                "name": "OFC",
                "version": "1.0",
                "uniqueDataKeys": ["email"]
            },
            "roleList":
            [
                "ROLE_USER"
            ],
            "token": "3bfb25b7a9c40e895b7121c30fdfbaded84fbf5f12b88788839b4011c8ca3ee189abe5aa4b82d92c",
            "tokenDate": 1387553949708,
            "tokenExpirationDate": 1387554190248,
            "credentialList":
            [
                {
                    "identity" : "deviceID",
                    "domain" : "DEVICE",
                    "password": "",
                    "accessToken": null
                },
                {
                    "identity" : "identity@mail.com",
                    "domain" : "INTERNAL",
                    "connected" : true,
                    "password": "",
                    "accessToken": null
                }    
            ]    
        }
        
## Authentication [/identity/rest/auth/subscribe]
    
### Subscribe and connect to the service [POST]

+ This verb will throw an error if credential already exist.
+ And if there is an error with the syntaxe of the data
+ A mandatory header 'X-SocialAPI-Service-Name' is required
+ Identity must be an email
+ Password must have at least 8 characters

+ Request (application/json)

    + Headers
    
            X-SocialAPI-Service-Name: name of the service

    + Body
    
            {
                "data" : {
                    "name":"jean",
                    "lastname":"blaguin"
                },
                "identity" : "identity@mail.com",
                "password" : "12345678",
                "role": "ROLE_USER"
            }

+ Response 200 (application/json)

        {
            "id": 56,
            "data" : {
                "name":"jean",
                "lastname":"blaguin"
            },
            "service": {
                "id": 2,
                "name": "OFC",
                "version": "1.0",
                "uniqueDataKeys": ["email"]
            },
            "roleList":
            [
                "ROLE_USER"
            ],
            "token": "3bfb25b7a9c40e895b7121c30fdfbaded84fbf5f12b88788839b4011c8ca3ee189abe5aa4b82d92c",
            "tokenDate": 1387553949708,
            "tokenExpirationDate": 1387554190248,
            "credentialList":
            [
                {
                    "identity" : "identity@mail.com",
                    "domain" : "internal",
                    "connected" : true,
                    "id" : 57,
                    "userId" : 56,
                    "password": "",
                    "accessToken": null
                }    
            ]    
        }

## Authentication [/identity/rest/auth/bydeviceid/{deviceId}?tokenOnly={tokenOnly}&noData={noData}]

+ Parameters

    + deviceId (required, string, `my-dummy-id`) ... String `deviceid` of the device which want to login.
    + tokenOnly (boolean, `token`) ... Boolean if true, this verb will only return "token", "tokenDate" and "tokenExpirationDate" fields. False by default.
    + noData (boolean, `noData`) ... Boolean if true, the data field is not send in response. False by default.

### Connection with a device identifier [POST]

+ User is automatically created if not exists.
+ A mandatory header 'X-SocialAPI-Service-Name' is required

+ Request

    + Headers
    
            X-SocialAPI-Service-Name: name of the service

+ Response 200 (application/json)

        {
            "id": 57,
            "data" : {
                "name":"jean",
                "lastname":"blaguin"
            },
            "service": {
                "id": 2,
                "name": "OFC",
                "version": "1.0",
                "uniqueDataKeys": ["email"]
            },
            "roleList":
            [
                "ROLE_USER"
            ],
            "token": "838f643b59b2fae6a0b18299a74945c3789fa2eb597c174808656da01863b410571dedd94c155d01",
            "tokenDate": 1387554090248,
            "tokenExpirationDate": 1387554190248,
            "credentialList":
            [
                {
                    "identity": "011554e6-2fe0-4e49-b2c1-468d12edff88",
                    "domain": "device",
                    "connected": true,
                    "id": 58,
                    "userId": 57,
                    "password": "",
                    "accessToken": "deviceId"
                }
            ]
        }
        
## Login [/identity/rest/auth/logout]

### Logout from the service [GET]

+ Needs ROLE_USER

+ Request

    + Headers
    
            token: the token of currently connected user
            
+ Response 200 (application/json)

        {"result": "Logout with success"}
        
## Login [/identity/rest/auth/login]

### Log to the service [POST]

+ A mandatory header 'X-SocialAPI-Service-Name' is required
+ A Json object must be posted {identity: "", password: ""}
+ The 'identity' is the user internal credential 'identity' field
+ Identity must be an email
+ Password must have at least 8 characters

+ Request

    + Headers
    
            X-SocialAPI-Service-Name: name of the service
            
+ Response 200 (application/json)

        {
            "id": 56,
            "data" : {
                "name":"jean",
                "lastname":"blaguin"
            },
            "service": {
                "id": 2,
                "name": "OFC",
                "version": "1.0",
                "uniqueDataKeys": ["email"]
            },
            "roleList":
            [
                "ROLE_USER"
            ],
            "token": "3bfb25b7a9c40e895b7121c30fdfbaded84fbf5f12b88788839b4011c8ca3ee189abe5aa4b82d92c",
            "tokenDate": 1387553949708,
            "tokenExpirationDate": 1387554190248,
            "credentialList":
            [
                {
                    "identity" : "identity@mail.com",
                    "domain" : "internal",
                    "connected" : true,
                    "id" : 57,
                    "userId" : 56,
                    "password": "",
                    "accessToken": null
                }    
            ]    
        }

## Social disconnection [/identity/rest/auth/social/disconnect/{domain}]

+ Parameters

    + domain (required, string, `FACEBOOK`) ... The social `domain` to disconnect.

### Remove the social connection for this user [GET]

+ User must at least have one credential after disconnection, otherwise an exception is thrown
+ If user have no credential for {domain}, an exception is thrown
+ If user has multiple credential for the same domain, all credentials will be removed

+ Request

    + Headers
    
            token: the token of currently connected user
            
+ Response 200 (application/json)
    
        {
            "id": 56,
            "data" : {
                "name":"jean",
                "lastname":"blaguin"
            },
            "service": {
                "id": 2,
                "name": "OFC",
                "version": "1.0",
                "uniqueDataKeys": ["email"]
            },
            "roleList":
            [
                "ROLE_USER"
            ],
            "token": "3bfb25b7a9c40e895b7121c30fdfbaded84fbf5f12b88788839b4011c8ca3ee189abe5aa4b82d92c",
            "tokenDate": 1387553949708,
            "tokenExpirationDate": 1387554190248,
            "credentialList":
            [
                {
                    "identity" : "identity@mail.com",
                    "domain" : "INTERNAL",
                    "connected" : true,
                    "id" : 57,
                    "userId" : 56,
                    "password": "",
                    "accessToken": null
                }    
            ]    
        }

## Social connection url [/identity/rest/auth/social/connect/{domain}?returnUrl={returnUrl}]

+ Parameters

    + domain (required, string, `facebook`) ... The social `domain` where user want to authenticate, must be a value in (FACEBOOK, LINKEDIN, GOOGLE, TWITTER).
    + returnUrl (string, `http://www.socialapi.com`) ... An url where return the user after the connection to the social network.

### Start OAuth dance [GET]

+ This will start the OAuth dance.
+ Client applications will redirect the user to this url to authenticate on the social network.
+ An url parameter "success" is returned at the end of the OAuth dance (verb: /identity/rest/auth/social/oauthcode), it contains true if user is correctly connected.
+ Url parameters returned: displayName, permissions, imageUrl, profileUrl
+ Needs ROLE_USER
+ If returnUrl specified, all parameters are transfered to this url
+ Only FACEBOOK and GOOGLE are supported for now
+ Social applications are specified by properties in the identity.properties file, these are :
+ - auth.socialconnect.facebook.appId
+ - auth.socialconnect.google.appId
+ - auth.socialconnect.twitter.appId
+ All device credentials of the connected user is moved to a new user

+ Request

    + Headers
    
            token: the token of currently connected user
            
+ Response 302


## Social connection url [/identity/rest/auth/social/confirm/{token}]

+ Parameters

    + token (required, string, `132154312321`) ... The token of the current connected user.

### Social callback [GET]

+ This verb is only called by socialAPI. Do not call directly.

+ Request (application/json)

    + Body
    
            { oauthobject: "" }
            
+ Response 200 (application/json)
    
        {
            "result": "ok"
        }


## Social connection url [/identity/rest/auth/social/oauthcode]

### OAuth end process url [GET]

+ This verb will be called at the end of the oauth dance. Do not call directly.
+ If a "returnUrl" parameter is passed to the /identity/rest/auth/social/connect/ verb, a redirect occurs here.
+ An url parameter "success" is returned and contains true if user is correctly connected.
+ Other url parameters returned: displayName, permissions, imageUrl, profileUrl.

+ Response 200 (text/plain)
    
        xxx is now connected on the 'yyy' social network.

+ Response 302

        Redirection to the "returnUrl" parameter. Passed to the /identity/rest/auth/social/connect/ verb at the beginning of the OAuth dance.

# Group User

User resources

## Current user [/identity/rest/user]

### Create a user [POST]

+ Needs ROLE_ADMIN
+ A mandatory header 'X-SocialAPI-Service-Name' is required

+ Request (application/json)

    + Headers
    
            X-SocialAPI-Service-Name: name of the service
            token: the token of currently connected user

    + Body
    
            {
                "data" : {
                    "name":"jean",
                    "lastname":"blaguin"
                },
                "identity" : "identity@mail.com",
                "password" : "12345678"
            }

+ Response 200 (application/json)

        {
            "id": 56,
            "data" : {
                "name":"jean",
                "lastname":"blaguin"
            },
            "service": {
                "id": 2,
                "name": "OFC",
                "version": "1.0",
                "uniqueDataKeys": ["email"]
            },
            "roleList":
            [
                "ROLE_USER"
            ],
            "token": "3bfb25b7a9c40e895b7121c30fdfbaded84fbf5f12b88788839b4011c8ca3ee189abe5aa4b82d92c",
            "tokenDate": 1387553949708,
            "tokenExpirationDate": 1387554190248,
            "credentialList":
            [
                {
                    "identity" : "identity@mail.com",
                    "domain" : "internal",
                    "connected" : true,
                    "id" : 57,
                    "userId" : 56,
                    "password": "",
                    "accessToken": null
                }    
            ]    
        }

### Get the current connected user [GET]

+ Request

    + Headers
    
            token: the token of currently connected user
            tokenRefresh: optionnal, if true, token of the currently connected user is refreshed

+ Response 200 (application/json)

        {
            "id": 56,
            "data" : {
                "name":"jean",
                "lastname":"blaguin"
            },
            "service": {
                "id": 2,
                "name": "OFC",
                "version": "1.0",
                "uniqueDataKeys": ["email"]
            },
            "roleList":
            [
                "ROLE_USER"
            ],
            "token": "3bfb25b7a9c40e895b7121c30fdfbaded84fbf5f12b88788839b4011c8ca3ee189abe5aa4b82d92c",
            "tokenDate": 1387553949708,
            "tokenExpirationDate": 1387554190248,
            "credentialList":
            [
                {
                    "identity" : "identity@mail.com",
                    "domain" : "internal",
                    "connected" : true,
                    "id" : 57,
                    "userId" : 56,
                    "password": "",
                    "accessToken": null
                }    
            ]    
        }


### Update the current connected user [PUT]

+ Request (application/json)

    + Headers
    
            token: the token of currently connected user
            tokenRefresh: optionnal, if true, token of the currently connected user is refreshed
            
    + Body
    
            {
                "id": "1",
                "data" : {
                    "name":"jean",
                    "lastname":"blaguin"
                }
            }
            
+ Response 200 (application/json)

        {
            id: 1,
            "data" : {
                "name":"jean",
                "lastname":"blaguin"
            },
            roleList:[
                "ROLE_USER"
            ],
            "token": "3bfb25b7a9c40e895b7121c30fdfbaded84fbf5f12b88788839b4011c8ca3ee189abe5aa4b82d92c",
            "tokenDate": 1387553949708,
            "tokenExpirationDate": 1387554190248,
            credentialList: [
                {
                    identity: "identity@mail.com",
                    domain: "internal",
                    connected: true
                },
                {
                    identity: "mydummyguididentity",
                    domain: "device",
                    connected: false
                }
            ]
        }
        
## Current user data [/identity/rest/user/data]

### Retreive user data [GET]

+ Retreive all data of the current connected user as an hashmap

+ Request

    + Headers
    
            token: the token of currently connected user
            tokenRefresh: optionnal, if true, token of the currently connected user is refreshed
          
+ Response 200 (application/json)

        {
            "firstname": "Juan",
            "lastname": "Maria",
            "avatar": "http://urltomyavatar.com/image.jpg"
        }
        
### Update user data [PUT]

+ Update user data.
+ All existing data is kept. New data is merged with existing one, if a conflict occurs (same key) value is overwritten.
+ If user has no data, data is created.
+ Unity constraint is applied on fiedls that registered in the associated service.

+ Request (application/json)

    + Headers
    
            token: the token of currently connected user
            tokenRefresh: optionnal, if true, token of the currently connected user is refreshed

    + Body
    
            {
                "firstname": "Juan"
            }
    
+ Response 200 (application/json)

        {
            "result": "data updated"
        }

## Data value by key [/identity/rest/user/data/{key}]

+ Parameters

    + key (required, string, `mykey`) ... `key` of the data to retrieve.

### Retreive data for this key [GET]

+ Request

    + Headers
    
            token: the token of currently connected user
            tokenRefresh: optionnal, if true, token of the currently connected user is refreshed
          
+ Response 200 (application/json)

        {
            "value": "Juan"
        }


### Update data for this key [PUT]

+ Request

    + Headers
    
            token: the token of currently connected user
            tokenRefresh: optionnal, if true, token of the currently connected user is refreshed

    + Body

            {
                "value": "Juan"
            } 

+ Response 200 (application/json)

        {
            "result": "data updated"
        } 
        
### Remove data for this key [DELETE]

+ Data will be removed for this key.

+ Request

    + Headers
    
            token: the token of currently connected user
            tokenRefresh: optionnal, if true, token of the currently connected user is refreshed

+ Response 200 (application/json)

        {
            "result": "data removed"
        } 
        
## Single User by its id [/identity/rest/user/{user_id}]

+ Parameters

    + user_id (required, number, `1`) ... Number `id` of the user.

### Retreive single user [GET]

+ Needs ROLE_ADMIN could retreive any user but ROLE_USER could only get its own (or use /identity/rest/user verb).

+ Request

    + Headers
    
            token: the token of currently connected user
            
+ Response 200 (application/json)

        {
            "id": 1,
            "roleList": [
                "ROLE_USER"
            ],
            "token": "3bfb25b7a9c40e895b7121c30fdfbaded84fbf5f12b88788839b4011c8ca3ee189abe5aa4b82d92c",
            "tokenDate": 1387553949708,
            "tokenExpirationDate": 1387554190248,
            "credentialList": [
                {
                    "identity": "identity@mail.com",
                    "domain": "internal",
                    "connected": true
                },
                {
                    "identity": "mydummyguididentity",
                    "domain": "device",
                    "connected": false
                }
            ]
        }

### Update a user [PUT]

+ ROLE_ADMIN could update any user but ROLE_USER could only update its own.

+ Request (application/json)

    + Headers
    
            token: the token of currently connected user
            
    + Body
    
            {
                "id": "1",
                "data": {
                    "firstname": "name"
                }
            }
            
+ Response 200 (application/json)

        {
            id: 1,
            "data": {
                "firstname": "name"
            },
            roleList:[
                "ROLE_USER"
            ],
            "token": "3bfb25b7a9c40e895b7121c30fdfbaded84fbf5f12b88788839b4011c8ca3ee189abe5aa4b82d92c",
            "tokenDate": 1387553949708,
            "tokenExpirationDate": 1387554190248,
            credentialList: [
                {
                    identity: "identity@mail.com",
                    domain: "internal",
                    connected: true
                },
                {
                    identity: "mydummyguididentity",
                    domain: "device",
                    connected: false
                }
            ]
        }
        
### Delete single user [DELETE]

+ Needs ROLE_ADMIN

+ Request

    + Headers
    
            token: the token of currently connected user
            
+ Response 200 (application/json)

        {
            "result" : "User Deleted"
        }
        
## Current user data [/identity/rest/user/{user_id}/data]

+ Parameters

    + user_id (required, number, `1`) ... Number `id` of the user.

### Retreive user data [GET]

+ Needs ROLE_ADMIN.
+ Retreive all data of the current connected user as an hashmap.

+ Request

    + Headers
    
            token: the token of currently connected user
          
+ Response 200 (application/json)

        {
            "firstname": "Juan",
            "lastname": "Maria",
            "avatar": "http://urltomyavatar.com/image.jpg"
        }
        
### Update user data [PUT]

+ Needs ROLE_ADMIN.
+ Update user data.
+ All existing data is kept. New data is merged with existing one, if a conflict occurs (same key) value is overwritten.
+ If user has no data, data is created.
+ Unity constraint is applied on fiedls that registered in the associated service.

+ Request (application/json)

    + Headers
    
            token: the token of currently connected user

    + Body
    
            {
                "firstname": "Juan"
            }
    
+ Response 200 (application/json)

        {
            "result": "data updated"
        }

## Data value by key [/identity/rest/user/{user_id}/data/{key}]

+ Parameters

    + user_id (required, number, `1`) ... Number `id` of the user.

+ Parameters

    + key (required, string, `mykey`) ... `key` of the data to retrieve.

### Retreive data for this key [GET]

+ Needs ROLE_ADMIN

+ Request

    + Headers
    
            token: the token of currently connected user
          
+ Response 200 (application/json)

        {
            "value": "Juan"
        }


### Update data for this key [PUT]

+ Needs ROLE_ADMIN

+ Request

    + Headers
    
            token: the token of currently connected user

    + Body

            {
                "value": "Juan"
            } 

+ Response 200 (application/json)

        {
            "result": "data updated"
        } 
        
### Remove data for this key [DELETE]

+ Needs ROLE_ADMIN
+ Data will be removed for this key.

+ Request

    + Headers
    
            token: the token of currently connected user

+ Response 200 (application/json)

        {
            "result": "data removed"
        } 
        
## User List [/identity/rest/user/list?offset=0&count=5]

+ Parameters

    + offset (required, number, `0`) ... First element of the list
    + count (required, number, `5`) ... Number of element for the list

### Retreive user list [GET]

+ Needs ROLE_ADMIN

+ Request

    + Headers
    
            token: the token of currently connected user
            
+ Response 200 (application/json)

        {
            "data": 
                [
                    {
                        id: 1,
                        roleList: [
                            "ROLE_USER"
                        ],
                        credentialList: [
                            {
                                identity: "identity@mail.com",
                                domain: "internal",
                                connected: true
                            },
                            {
                                identity: "mydummyguididentity",
                                domain: "device",
                                connected: false
                            }
                        ]
                    },
                    {
                        id: 2,
                        roleList: [
                            "ROLE_USER"
                        ],
                        credentialList: [
                            {
                                identity: "identity@mail.com",
                                domain: "internal",
                                connected: true
                            }
                        ]
                    }
                ],
            "nbElt": 2,
            "offset": 0,
            "nbTotal": 2
        }


## User List [/identity/rest/user/resetPassword/{identity}]

+ Parameters

    + identity (required, string, `identity@mail.com`) ... Identity who wants reset his password (for INTERNAL credential)

### Reset password [GET]

+ This will reset the password of the user and send it on his identity (email) 
+ A mandatory header 'X-SocialAPI-Service-Name' is required

+ Request

    + Headers
    
            X-SocialAPI-Service-Name: name of the service


+ Response 200 (application/json)

        {
            "result": "Email sent"
        }

## User role [/identity/rest/user/{user_id}/role/{role_id}]

+ Parameters

    + user_id (required, number, `1`) ... Number `id` of the user.
    + role_id (required, string, `ROLE_USER`) ... Role of the user.

### Set the role for a user [POST]

+ If ROLE_ADMIN is added, ROLE_USER is added too.
+ If a lower role is set, all higher roles are deleted.
+ If user has already at the role {role_id} no error is thrown.
+ Needs ROLE_ADMIN to use this verb.

+ Request

    + Headers
    
            token: the token of currently connected user
            
+ Response 200 (application/json)

        {
            "result": "Role changed"
        }


## Single User by identity [/identity/rest/user/byidentity/{identity}/{domain}]

+ Parameters

    + identity (required, string, `identity`) ... String `identity` of the user to search.
    + domain (required, string, `domain`) ... String `domain` where search (could be: INTERNAL, DEVICE or SOCIAL).

### Retrieve single user by his identity [GET]

+ Needs ROLE_USER
+ Search is strict

+ Response 200 (application/json)

        {
            id: 1,
            roleList: [
                "ROLE_USER"
            ],
            credentialList: [
                {
                    identity: "identity@mail.com",
                    domain: "internal",
                    connected: true
                },
                {
                    identity: "mydummyguididentity",
                    domain: "device",
                    connected: false
                }
            ]
        }
       
## Single User by identity [/identity/rest/user/byidentity/{identity}]

+ Parameters

    + identity (required, string, `identity`) ... String `identity` of the user to search.

### Retrieve single user by his identity [GET]

+ Needs ROLE_USER
+ Search is strict

+ Response 200 (application/json)

        {
            id: 1,
            roleList: [
                "ROLE_USER"
            ],
            credentialList: [
                {
                    identity: "identity@mail.com",
                    domain: "internal",
                    connected: true
                },
                {
                    identity: "mydummyguididentity",
                    domain: "device",
                    connected: false
                }
            ]
        }

## User internal credential [/identity/rest/user/{user_id}/credential/internal]

+ Parameters

    + user_id (required, number, `1`) ... Number `id` of the user.
    
### Create internal credential [POST]

+ Add internal credential to this user

+ Request (application/json)

    + Headers
    
            token: the token of currently connected user
    + Body
    
            {
                "identity": "identity@mail.com"
                "password": "123"
            }
            
+ Response 200 (application/json)

            {
                id: 1,
                roleList: [
                    "ROLE_ADMIN"
                ],
                credentialList: [
                    {
                        identity: "identity@mail.com",
                        domain: "internal",
                        connected: false
                    }
                ]
            }

### Update internal credential [PUT]

+ Update the internal credential of this user

+ Request (application/json)

    + Headers
    
            token: the token of currently connected user
    + Body
    
            {
                "identity": "identity@mail.com"
                "password": "123"
            }
            
+ Response 200 (application/json)

            {
                id: 1,
                roleList: [
                    "ROLE_ADMIN"
                ],
                credentialList: [
                    {
                        identity: "identity@mail.com",
                        domain: "internal",
                        connected: false
                    }
                ]
            }

## User internal credential [/identity/rest/user/credential/internal]

### Update internal credential [PUT]

+ Update the internal credential of the connected user

+ Request (application/json)

    + Headers
    
            token: the token of currently connected user
    + Body
    
            {
                "identity": "identity@mail.com"
                "password": "123"
                "data" : {
                    "nickname":"jean",
                    "lastname":"blaguin"
                }
            }
            
+ Response 200 (application/json)

            {
                "result": "Credential updated"
            }
            
## User credential [/identity/rest/user/{user_id}/credential?domain={domain}&identity={identity}]

+ Parameters

    + user_id (required, number, `1`) ... Number `id` of the user.
    + domain (required, string, `internal`) ... Domain of the credential
    + identity (required, string, `identity@mail.com`) ... Identity of the credential

### Delete the credential [DELETE]

+ Needs ROLE_ADMIN

+ Request

    + Headers
    
            token: the token of currently connected user
            
+ Response 200 (application/json)

        {
            "result": "Credential deleted"
        }